# Generated by Django 5.0.4 on 2024-04-21 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_category', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_title', models.CharField(max_length=100, null=True)),
                ('m_desc', models.TextField(null=True)),
                ('m_DOB', models.DateField(null=True)),
                ('m_act', models.CharField(max_length=100, null=True)),
                ('m_youtube', models.TextField(null=True)),
                ('m_img', models.ImageField(null=True, upload_to='gallery/')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('m_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies_app.movies')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_name', models.CharField(max_length=20, null=True)),
                ('re_feed', models.CharField(max_length=100, null=True)),
                ('re_post', models.CharField(max_length=200, null=True)),
                ('re_rating', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('re_status', models.CharField(max_length=20, null=True)),
                ('re_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_fname', models.CharField(max_length=30, null=True)),
                ('e_lname', models.CharField(max_length=30, null=True)),
                ('e_email', models.EmailField(max_length=254, null=True)),
                ('e_post', models.CharField(max_length=50, null=True)),
                ('e_photo', models.ImageField(null=True, upload_to='image/')),
                ('e_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies_app.movie_cart')),
                ('e_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies_app.category')),
                ('e_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
