# Generated by Django 5.0.4 on 2024-04-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='re_status',
        ),
        migrations.AddField(
            model_name='review',
            name='re_DOB',
            field=models.DateField(null=True),
        ),
    ]
