# Generated by Django 5.0.4 on 2024-04-21 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_remove_review_re_status_review_re_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='re_movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies_app.movies'),
        ),
        migrations.AddField(
            model_name='users',
            name='e_movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies_app.movies'),
        ),
    ]
